apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot
          image: sankkket24/spring-boot-k8s:v1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
